// Seed data + token constants for Luida web dashboard.
// All Korean copy follows the "tavern NPC" voice from spec §8.

export const LUIDA_TOKENS = {
  themes: {
    navy: {
      label: '블랙 (정통)',
      bg: '#000000',
      win: '#000000',
      winAlt: '#16161F',
      border: '#FFFFFF',
      text: '#FFFFFF',
      dim: '#9CA3AF',
      gold: '#FCD34D',
      green: '#4ADE80',
      yellow: '#FACC15',
      red: '#EF4444',
      blue: '#60A5FA',
      pink: '#F472B6',
    },
    slate: {
      label: '슬레이트',
      bg: '#0A0E14',
      win: '#1E2530',
      winAlt: '#262E3A',
      border: '#E5E7EB',
      text: '#FFFFFF',
      dim: '#9CA3AF',
      gold: '#FCD34D',
      green: '#4ADE80',
      yellow: '#FACC15',
      red: '#EF4444',
      blue: '#60A5FA',
      pink: '#F472B6',
    },
    purple: {
      label: '바이올렛',
      bg: '#0E0420',
      win: '#2D1065',
      winAlt: '#3B158A',
      border: '#FFFFFF',
      text: '#FFFFFF',
      dim: '#C4B5FD',
      gold: '#FDE047',
      green: '#86EFAC',
      yellow: '#FACC15',
      red: '#FB7185',
      blue: '#7DD3FC',
      pink: '#F0ABFC',
    },
    forest: {
      label: '심야 숲',
      bg: '#020A06',
      win: '#063C2A',
      winAlt: '#0B5235',
      border: '#FFFFFF',
      text: '#FFFFFF',
      dim: '#BBF7D0',
      gold: '#FDE047',
      green: '#A7F3D0',
      yellow: '#FACC15',
      red: '#FCA5A5',
      blue: '#7DD3FC',
      pink: '#F0ABFC',
    },
  },
};

export const LUIDA_DATA = {
  adventurers: [
    {
      name: 'agora',
      class: 'Frontend Knight',
      classKr: '프론트 기사',
      icon: '🛡',
      role: 'worker',
      status: 'busy',
      level: 27,
      hp: { current: 84, max: 100 },
      mp: { current: 32, max: 50 },
      workspace_id: 'cmux/agora-01',
      repo: 'community-web-agora',
      last_seen_label: '방금 전',
      current_quest: 142,
    },
    {
      name: 'admin',
      class: 'API Mage',
      classKr: 'API 마법사',
      icon: '📜',
      role: 'worker',
      status: 'busy',
      level: 31,
      hp: { current: 62, max: 100 },
      mp: { current: 44, max: 60 },
      workspace_id: 'cmux/admin-02',
      repo: 'community-web-admin',
      last_seen_label: '방금 전',
      current_quest: 143,
    },
    {
      name: 'kontrol',
      class: 'Infra Cleric',
      classKr: '인프라 사제',
      icon: '⚙',
      role: 'worker',
      status: 'idle',
      level: 19,
      hp: { current: 100, max: 100 },
      mp: { current: 50, max: 50 },
      workspace_id: 'cmux/kontrol-01',
      repo: 'community-kontrol',
      last_seen_label: '2분 전',
      current_quest: null,
    },
    {
      name: 'lantern',
      class: 'Search Ranger',
      classKr: '검색 순찰자',
      icon: '🏹',
      role: 'worker',
      status: 'busy',
      level: 14,
      hp: { current: 41, max: 100 },
      mp: { current: 18, max: 40 },
      workspace_id: 'cmux/lantern-01',
      repo: 'lantern-search',
      last_seen_label: '방금 전',
      current_quest: 141,
    },
    {
      name: 'forge',
      class: 'Build Smith',
      classKr: '빌드 대장장이',
      icon: '🔨',
      role: 'worker',
      status: 'offline',
      level: 22,
      hp: { current: 0, max: 100 },
      mp: { current: 0, max: 40 },
      workspace_id: 'cmux/forge-01',
      repo: 'community-forge',
      last_seen_label: '14분 전',
      current_quest: null,
    },
    {
      name: 'brain',
      class: 'Chronicler',
      classKr: '연감 기록자',
      icon: '📖',
      role: 'brain',
      status: 'idle',
      level: 38,
      hp: { current: 100, max: 100 },
      mp: { current: 80, max: 80 },
      workspace_id: 'cmux/brain',
      repo: 'luida-brain',
      last_seen_label: '방금 전',
      current_quest: null,
    },
  ],

  quests: [
    {
      id: 143,
      to: 'admin',
      brief: 'Prisma 스키마에 chronicle_events 테이블 추가하고 마이그레이션 생성',
      branch: 'feat/chronicle-events-table',
      status: 'running',
      progress_pct: 42,
      progress_label: '5개 파일 중 2개 처리 중',
      pr_url: null,
      created_label: '12분 전',
    },
    {
      id: 142,
      to: 'agora',
      brief: '의뢰 상세 페이지에서 부모 quest 트리를 시각화해주세요',
      branch: 'feat/quest-tree-view',
      status: 'running',
      progress_pct: 71,
      progress_label: '컴포넌트 작성 완료 · 테스트 추가 중',
      pr_url: null,
      created_label: '38분 전',
    },
    {
      id: 141,
      to: 'lantern',
      brief: '검색 인덱스 재빌드 작업이 8시간째 멈춰있다 — 원인 분석 후 보고',
      branch: 'hotfix/index-rebuild-stall',
      status: 'needs_approval',
      progress_pct: 100,
      progress_label: '원인 파악 · 사용자 승인 대기 중',
      pr_url: null,
      created_label: '1시간 전',
    },
    {
      id: 140,
      to: 'agora',
      brief: '대시보드 푸터에 SSE 연결 상태 인디케이터 추가',
      branch: 'chore/sse-status-indicator',
      status: 'pr_ready',
      progress_pct: 100,
      progress_label: 'PR #284 작성 완료',
      pr_url: 'https://github.com/karrot/luida/pull/284',
      created_label: '2시간 전',
    },
    {
      id: 139,
      to: 'kontrol',
      brief: 'staging 환경 nginx 캐시 TTL을 60s → 30s로 조정',
      branch: 'ops/nginx-cache-tune',
      status: 'completed',
      progress_pct: 100,
      progress_label: '완료 · staging 배포 확인됨',
      pr_url: 'https://github.com/karrot/luida/pull/282',
      created_label: '오늘 09:14',
    },
    {
      id: 138,
      to: 'forge',
      brief: 'Bun 1.2 업그레이드 후 esbuild 충돌 해결',
      branch: 'chore/bun-1.2-upgrade',
      status: 'failed',
      progress_pct: 60,
      progress_label: 'typecheck 실패 · 모험가 다운',
      pr_url: null,
      created_label: '오늘 08:02',
    },
    {
      id: 137,
      to: 'admin',
      brief: '관리자 페이지 권한 매트릭스 리팩토링',
      branch: 'refactor/permission-matrix',
      status: 'reviewing',
      progress_pct: 90,
      progress_label: 'self-review 진행 중',
      pr_url: null,
      created_label: '어제',
    },
    {
      id: 136,
      to: 'agora',
      brief: '게시글 작성 폼 자동 저장 인터벌 30s → 10s',
      branch: 'feat/autosave-tighter',
      status: 'completed',
      progress_pct: 100,
      progress_label: '완료',
      pr_url: 'https://github.com/karrot/luida/pull/280',
      created_label: '어제',
    },
    {
      id: 135,
      to: 'lantern',
      brief: '검색 결과 한자 동음이의어 처리 개선',
      branch: 'feat/hanja-disambig',
      status: 'aborted',
      progress_pct: 18,
      progress_label: '사용자 요청으로 중단',
      pr_url: null,
      created_label: '어제',
    },
  ],

  events: [
    { t: '14:32', icon: '⚔', kind: 'dispatch', text: '🍺 새 의뢰 #143이 admin에게 전달되었습니다.' },
    { t: '14:30', icon: '🌀', kind: 'progress', text: 'agora가 의뢰 #142 진행 중 — 컴포넌트 3개를 작성했습니다.' },
    { t: '14:18', icon: '⚠', kind: 'alert', text: '⚠ lantern이 함정에 빠진 듯합니다 — 사용자 승인을 기다립니다.' },
    { t: '14:02', icon: '✓', kind: 'ack', text: 'agora가 의뢰 #140을 완수하고 돌아왔어요. PR이 게시판에 붙었습니다.' },
    { t: '13:47', icon: '💡', kind: 'proposal', text: '연감이 새 패턴을 발견했습니다 — "agora schema → admin codegen" (신뢰도 7/10).' },
    { t: '13:21', icon: '🏁', kind: 'info', text: 'kontrol이 의뢰 #139를 가볍게 처리했습니다. 조용한 오후네요.' },
    { t: '12:58', icon: '💀', kind: 'alert', text: '💀 forge가 쓰러졌습니다 (typecheck 실패). HP를 회복할 시간입니다.' },
    { t: '12:30', icon: '🌀', kind: 'aborted', text: '🌀 의뢰 #135가 무효화되었습니다. 사용자가 길을 바꾸셨군요.' },
    { t: '11:55', icon: '📜', kind: 'dispatch', text: '새 의뢰가 게시판에 붙었습니다 — admin 행 #137.' },
    { t: '09:14', icon: '✓', kind: 'ack', text: 'kontrol이 의뢰 #139를 받아들였습니다. staging 점검 시작.' },
  ],

  patterns: [
    {
      id: 'p-1',
      title: 'agora schema → admin codegen',
      desc: 'agora 저장소의 prisma/**가 바뀐 뒤 평균 14분 안에 admin이 codegen 의뢰를 받았습니다 (최근 9회 / 12회 일치).',
      confidence: 7,
      kind: 'proposed',
    },
    {
      id: 'p-2',
      title: 'lantern index rebuild → kontrol cache flush',
      desc: 'lantern이 search index를 재빌드한 직후 캐시 무효화가 필요했습니다 (4회 / 4회).',
      confidence: 9,
      kind: 'proposed',
    },
    {
      id: 'p-3',
      title: 'PR 머지 후 staging 배포 알림',
      desc: '활성 룰 — 인간 정의. 최근 3일간 11번 트리거됨.',
      confidence: null,
      kind: 'active',
    },
  ],
};

// English mirror used when tweak.lang === 'en'.
export const LUIDA_I18N = {
  ko: {
    nav: ['무드보드', '디자인 토큰', '컴포넌트', '대시보드'],
    tabs: { adventurers: '모험가', quests: '의뢰 게시판', tavern: '주점 게시판', chronicle: '연감' },
    filters: ['전체', '진행중', '승인 필요', '완료', '실패'],
    cta: { approve: '승인', reject: '거절', promote: '룰로 승격', dismiss: '무시' },
    statusBadges: {
      pending: '대기', running: '진행중', reviewing: '검토중',
      needs_approval: '승인 필요', pr_ready: 'PR 완료',
      completed: '완료', failed: '실패', aborted: '중단',
    },
    statusBadgesAdv: { idle: '대기', busy: '의뢰중', offline: '오프라인' },
    emptyTavern: '오늘은 평화로운 하루입니다. 주점이 조용하네요. 🍺',
    welcome: '루이다의 주점에 오신 것을 환영합니다, 용사여.',
  },
  en: {
    nav: ['Moodboard', 'Tokens', 'Components', 'Dashboard'],
    tabs: { adventurers: 'Adventurers', quests: 'Quest Board', tavern: 'Tavern Log', chronicle: 'Chronicle' },
    filters: ['All', 'Active', 'Needs Approval', 'Done', 'Failed'],
    cta: { approve: 'APPROVE', reject: 'REJECT', promote: 'PROMOTE', dismiss: 'DISMISS' },
    statusBadges: {
      pending: 'PENDING', running: 'RUNNING', reviewing: 'REVIEW',
      needs_approval: 'APPROVE?', pr_ready: 'PR READY',
      completed: 'DONE', failed: 'FAILED', aborted: 'ABORTED',
    },
    statusBadgesAdv: { idle: 'IDLE', busy: 'BUSY', offline: 'OFFLINE' },
    emptyTavern: 'A peaceful day at the tavern. 🍺',
    welcome: "Welcome to Luida's Tavern, brave one.",
  },
};
